Month 9/step 1
pblHbKa/react-burger pull request #6
Opened 2022-12-14 21:55 UTC by pblHbKa

2022-12-15 10:36 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу по добавлению элементов авторизации в ваш проект, сделали удобный хук для них и настраиваемый компонент `ProtectedRoute`, корректно провели верстку новых страниц, так держать 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив **особое** внимание на следующие моменты:

- Следует проверять валидность **всех форм** и разрешать пользователю отправлять их только тогда, когда заполнены все обязательные поля (например см. https://disk.yandex.ru/i/zdGvYgSKggPPyw). Бэкенд, конечно, ответит ошибкой, в случае некорректных данных, но чем меньше запросов делаем - тем лучше для производительности всей системы в целом;
- **После обновления страницы** по F5 пользователь считается неавторизованным, хотя нужные токены присутствуют (см. https://disk.yandex.ru/i/Xc7uLFgjb-RPLQ);
- Путь `/reset-password` следует сделать доступным неавторизованным пользователям **только после** посещения маршрута `/forgot-password` и ввода адреса электронной почты для восстановления пароля;
- При отправке формы пользователя на сервер уходит только поле **имени**, электронная почта и пароль (только если он был изменен) **следует также отправлять** (см. https://disk.yandex.ru/i/U9w1lplNk6QD0g);
- Заказы могут делать только авторизованные пользователи, поэтому при создании заказа **следует подставлять токен** пользователя в заголовки запроса (см. https://disk.yandex.ru/i/DnrtLD4LfiDU-g);
- При переходе на 404 страницу (например Лента заказов), становится **невозможным** нажать на ссылки в хедере;
- У модального окна с подробностями об ингредиенте **отсутствует** заголовок (см. https://disk.yandex.ru/i/xjkkiAoUd7hEkg);
- Иконка активной ссылки в хедере **всегда белая** у конструктора, вне зависимости от текущего пути. Следует синхронизировать подсветку текста и иконки, согласно дизайну (см. https://disk.yandex.ru/i/D1o6EcEmmVcU-Q).
- Функция `updateToken` **не используется** в рамках проекта и токен при протухании не обновляется. При запросах, использующих `accessToken` следует проверять ответ сервера. и если время жизни токена истекло (код 403), то **выполнять запрос обновления** токена и повторять запрос, который не был выполнен успешно.

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- Файлы в папке `pages` лучше распределить по одноименным папкам, чтобы не держать все файлы в одном месте;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2022-12-15 10:36 UTC, randomroot commented on src/services/reduces/user.js
> +    const data = await authorization(userData).then((res) => {
🟡 **Можно улучшить:**

Т.к. переменная не используется, то можно просто оставить вызов с `await` без присвоения результата

2022-12-15 10:36 UTC, randomroot commented on src/services/reduces/user.js
> +const AuthContext = createContext(undefined);
🟡 **Можно улучшить:**

Использование контекста в данном случае возможно, но целесообразно проводить все операции в рамках хранилища Redux-a, чтобы все операции в рамках проекта были в одном месте :)

2022-12-15 10:36 UTC, randomroot commented on src/components/ingredients-category/ingredients-category.jsx
> +  group: PropTypes.arrayOf(ingredientType).isRequired,
🔴 **Нужно исправить:**

Значения массива, если они не предполагаются пустыми следует также указывать через `isRequired` 
```
arrayOf(item.isRequired).isRequired
```

2022-12-15 10:36 UTC, randomroot commented on src/pages/profile.jsx
> +            style={{ textAlign: "left" }}
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-12-15 10:36 UTC, randomroot commented on src/pages/profile.jsx
> +      setModified(true);
🟡 **Можно улучшить:**

Можно вынести в конец функции, чтобы не дублировать в каждом из веток `if`

2022-12-15 10:36 UTC, randomroot commented on src/utils/burger-api.js
> +    body: JSON.stringify({ email, name }),
🔴 **Нужно исправить:**

Следует также учитывать поле `password`

2022-12-15 10:36 UTC, randomroot commented on src/pages/profile.jsx
> +    auth.updateUserInfo({ name, user, password });
🔴 **Нужно исправить:**

В функцию `updateUserInfo` следует передавать `email`, вместо переменной `user` :)

2022-12-15 10:36 UTC, randomroot commented on src/pages/login.jsx
> +  if (auth.user) {
🟡 **Можно улучшить:**

Исходя из вашего кода данный функционал выполняет `ProtectedRoute`, поэтому его здесь можно не дублировать :)

2022-12-17 12:19 UTC, pblHbKa commented on src/services/reduces/user.js
> +    const data = await authorization(userData).then((res) => {
Исправлено

2022-12-17 12:21 UTC, pblHbKa commented on src/components/ingredients-category/ingredients-category.jsx
> +  group: PropTypes.arrayOf(ingredientType).isRequired,
Исправлено

2022-12-17 12:30 UTC, pblHbKa commented on src/pages/profile.jsx
> +            style={{ textAlign: "left" }}
Исправлено

2022-12-17 12:32 UTC, pblHbKa commented on src/pages/profile.jsx
> +      setModified(true);
Исправлено

2022-12-17 12:33 UTC, pblHbKa commented on src/utils/burger-api.js
> +    body: JSON.stringify({ email, name }),
Исправлено

2022-12-17 12:34 UTC, pblHbKa commented on src/pages/profile.jsx
> +    auth.updateUserInfo({ name, user, password });
Исправлено

2022-12-17 12:38 UTC, pblHbKa commented on src/pages/login.jsx
> +  if (auth.user) {
Исправлено

2022-12-18 20:40 UTC, pblHbKa commented on src/services/reduces/user.js
> +const AuthContext = createContext(undefined);
Исправлено

2022-12-19 12:20 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2022-12-22 20:58 UTC, merged